(defvar *long-clauses*
  '(((NOT B) (NOT M) O) ((NOT O) K (NOT J)) (B I J) (B C (NOT J))
    ((NOT I) P (NOT A)) (L A J) ((NOT G) L F) (A K (NOT M)) ((NOT F) D H)
    (P (NOT I) C) (K (NOT O) (NOT D)) ((NOT I) E D) ((NOT A) E (NOT P))
    ((NOT I) K P) ((NOT H) D A) (C B (NOT M)) (P (NOT F) B) ((NOT C) (NOT A) F)
    (M (NOT H) P) (D P C) ((NOT K) F P) (F (NOT I) P) (F O A) (F (NOT J) (NOT H))
    (J (NOT G) (NOT C)) ((NOT L) (NOT H) N) ((NOT J) (NOT N) (NOT P))
    ((NOT I) D (NOT K)) ((NOT A) (NOT J) (NOT I)) (D B P) (L E B) ((NOT P) E G)
    (E O (NOT C)) ((NOT M) E (NOT A)) (C I (NOT D)) (F (NOT O) K) ((NOT L) J P)
    (K N (NOT M)) (L (NOT O) P) ((NOT H) O I) (L D N) ((NOT M) L P) ((NOT L) I N)
    ((NOT I) (NOT E) (NOT F)) ((NOT D) (NOT J) (NOT P)) ((NOT I) B L)
    (D P (NOT J)) (O C N) (C D (NOT I)) ((NOT I) (NOT O) L) (E N C) (F A L)
    (L E (NOT H)) (F (NOT N) J) (K B (NOT D)) ((NOT I) D (NOT P)) (N K (NOT I))
    ((NOT O) L D) (C K (NOT G)) ((NOT K) D (NOT E)) ((NOT N) D (NOT G))
    ((NOT I) (NOT G) D) (D K (NOT G)) ((NOT B) A (NOT K)) (P (NOT A) (NOT D))
    (B (NOT I) D) (F (NOT J) (NOT N)) ((NOT L) N M) (L (NOT A) P)
    (P (NOT E) (NOT B)) (K C N) ((NOT C) J (NOT H)) (K P (NOT H)) (J D M)
    (N (NOT P) A) (F B E) ((NOT B) (NOT G) (NOT K)) (P M K) ((NOT H) (NOT L) E)
    ((NOT N) K (NOT A)) ((NOT A) B (NOT F)) (A (NOT J) (NOT O)) ((NOT D) A I)
    (A I O) (M (NOT F) K) (E (NOT P) (NOT A)) ((NOT J) (NOT H) D)
    (B (NOT J) (NOT H)) ((NOT H) (NOT G) (NOT J)) (F A C) (K (NOT H) (NOT J))
    ((NOT E) (NOT B) N) ((NOT D) (NOT C) N) (B N L) ((NOT L) (NOT J) (NOT N))
    ((NOT G) (NOT C) I)))

(defvar *short-clauses*
  '((F (NOT B) E) (C (NOT D) E) ((NOT G) F (NOT B)) (D C (NOT A)) (D F B)
    (D (NOT I) (NOT E)) ((NOT H) E I) ((NOT G) F I) (C F (NOT H)) (J G (NOT A))
    ((NOT H) E (NOT A)) (A (NOT F) E) ((NOT G) (NOT E) B) (E (NOT D) (NOT I))
    ((NOT G) I E) ((NOT G) (NOT B) E) (J D (NOT F)) (F (NOT H) E) (D (NOT H) E)
    ((NOT H) (NOT B) C) ((NOT E) I (NOT D)) (B (NOT F) (NOT A)) (E (NOT I) J)
    (E (NOT A) I) (D (NOT F) (NOT H)) (A H D) ((NOT D) G (NOT J)) (F D (NOT A))
    (C D F) ((NOT A) (NOT H) E)))
